w_pos_body: [20, 20, 80, 10, 10, 10]
w_pos_leg: [0.1, 0.1, 0.1]
w_vel_body: [0.7, 0.7, 0.7, 0.3, 0.3, 0.3]
w_vel_leg: [0.01, 0.01, 0.01]

w_pos_body_term: [200, 200, 800, 100, 100, 100]
w_pos_leg_term: [10, 10, 10]

w_vel_body_term: [7, 7, 7, 3, 3, 3]
w_vel_leg_term: [0.1, 0.1, 0.1]

w_u_leg: [2e-4, 2e-4, 2e-4]

w_foot_slip_clearance: 0.5

nsteps: 25
timestep: 0.02
max_iter: 4