w_pos_body: [10, 10, 10, 1, 1, 1]
w_pos_leg: [0, 0, 0]
w_vel_body: [1, 1, 1, 1, 1, 1]
w_vel_leg: [0.1, 0.1, 0.1]

w_pos_body_term: [10, 10, 10, 10, 10, 10]
w_pos_leg_term: [1, 1, 1]

w_vel_body_term: [1, 1, 1, 1, 1, 1]
w_vel_leg_term: [0.1, 0.1, 0.1]

w_u_leg: [1e-3, 1e-3, 1e-3]

w_foot_slip_clearance: 1.0
w_symmetric_control: 1e-2

kp_leg: [50, 50, 50]
kd_leg: [2, 2, 2]

nsteps: 40
timestep: 0.01
max_iter: 2

real_contact:
  contact_stiffness: 2000
  smoothing_factor: 0.01
  dissipation_velocity: 0.1
  stiction_velocity: 0.5
  friction_coefficient: 1.0

fake_contact:
  contact_stiffness: 2000
  smoothing_factor: 0.01
  dissipation_velocity: 0.1
  stiction_velocity: 0.5
  friction_coefficient: 1.0