w_pos: [1, 1, 1,
        10, 10, 10,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0]

w_vel: [1, 1, 1,
        1, 1, 1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1]

w_pos_term: [10, 10, 10,
              10, 10, 10,
              1, 1, 1,
              1, 1, 1,
              1, 1, 1,
              1, 1, 1]

w_vel_term: [1, 1, 1,
        1, 1, 1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1]

w_u_leg: [1e-4, 1e-4, 1e-4]